### ISSUE TITLE
Remove previous syntax ?

### ISSUE THREAD

**Issue by iamvdo** [iamvdo/postcss-opacity#3]
What about previous syntax version ?

``` css
.e {
    opacity: .5;
    filter: alpha(opacity=50);
}
```

become

``` css
.e {
    opacity: .5;
    -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=50)";
    filter: alpha(opacity=50);
}
```

Should we remove it ?
Old code have to be cleaned ?
