### ISSUE TITLE
Add option to disable transformation

### ISSUE THREAD

**Issue by niksy** [iamvdo/postcss-opacity#5]
Sometimes you don’t want to apply transformation but rather provide fallback through some other method.

Maybe something along the lines of adding special comment to selector which signals `postcss-opacity` not to apply transformation to current selector:

``` css
.foo {
    /* @postcss-opacity: disable */
    opacity:0.5;
}
```
